# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubm8core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubm8core.Plan'),
        ),
    ]
