# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubm8core', '0002_auto_20160917_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
