# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubm8core', '0003_plan_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='occurence',
        ),
        migrations.AddField(
            model_name='occurrence',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubm8core.Plan'),
        ),
    ]
