# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubm8core', '0008_pluralize_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(),
        ),
    ]
